server:
  port: 6001

eureka:
  instance:
    hostname: eureka6001.com  #eureka服务端实例名称
  client:
    registerWithEureka: true  #是否把自己注册到eureka
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6002.com:6002/eureka/
    instance:
      instance-id: eurker1      #设置实例名称，不暴露主机名
      prefer-ip-address: true   #访问路径时显示ip
      lease-renewal-interval-in-seconds: 1    # Erueka客户端向服务端发送心跳的时间间隔，单位秒 默认30s
      lease-expiration-duration-in-seconds: 2   # Eureka客户端在收到最后一次心跳后的等待时间上限，单位秒  默认90秒  超市将剔除
  server:
    #关闭注册中心的保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000  #心跳时间  超过2s  如果2s没有收到心跳 就会从注册中心剔除